version: '3.8'

services:
  meilisearch:
    image: getmeili/meilisearch:latest
    container_name: meilisearch
    restart: unless-stopped
    ports:
      - "${DOCKER_HOST_PORT}:${MEILI_PORT}"
    environment:
      - MEILI_ENV=${MEILI_ENV}
      - MEILI_MASTER_KEY=${MEILI_MASTER_KEY}
      - MEILI_LOG_LEVEL=${MEILI_LOG_LEVEL}
      - MEILI_HTTP_ADDR=0.0.0.0:${MEILI_PORT}
      - MEILI_NO_ANALYTICS=${MEILI_NO_ANALYTICS}
    volumes:
      - meilisearch_data:${MEILI_DB_PATH}
    networks:
      - meilisearch_network

  postgres:
    image: postgres:latest
    container_name: postgres_test
    restart: unless-stopped
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=testdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - meilisearch_network

volumes:
  meilisearch_data:
  postgres_data:

networks:
  meilisearch_network:
    driver: bridge
